(source gnu)
(source melpa)

(depends-on "ag")
(depends-on "escreen")
(depends-on "evil")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "flycheck-haskell")
(depends-on "grizzl")
(depends-on "haskell-mode")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "neotree")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "ws-butler")
